"""Extension tools."""

from .analyze_tools import (
    enter_analyze,
    exit_analyze,
    upsert_artifact,
)
from .confluence_tools import (
    confluence_download_attachment,
    confluence_get_attachments,
    confluence_get_page,
    confluence_get_page_by_title,
    confluence_get_page_children,
    confluence_get_spaces,
    confluence_search,
)
from .gerrit_tools import (
    gerrit_get_change,
    gerrit_get_change_detail,
    gerrit_get_change_diff,
    gerrit_get_change_messages,
    gerrit_get_file_content,
    gerrit_get_project_branches,
    gerrit_list_changes,
    gerrit_list_projects,
)
from .jira_tools import (
    jira_download_attachment,
    jira_get,
    jira_get_attachments,
    jira_get_comments,
    jira_get_projects,
    jira_get_transitions,
    jira_search,
)
from .opengrok_tools import (
    opengrok_list_projects,
    opengrok_read_file,
    opengrok_search_code,
    opengrok_search_definition,
    opengrok_search_path,
    opengrok_search_symbol,
)

EXT_TOOLS = [
    jira_search,
    jira_get,
    jira_get_transitions,
    jira_get_projects,
    jira_get_comments,
    jira_get_attachments,
    jira_download_attachment,
    confluence_search,
    confluence_get_page,
    confluence_get_page_by_title,
    confluence_get_spaces,
    confluence_get_page_children,
    confluence_get_attachments,
    confluence_download_attachment,
    gerrit_list_changes,
    gerrit_get_change,
    gerrit_get_change_detail,
    gerrit_get_change_diff,
    gerrit_get_change_messages,
    gerrit_get_file_content,
    gerrit_list_projects,
    gerrit_get_project_branches,
    opengrok_list_projects,
    opengrok_search_code,
    opengrok_search_definition,
    opengrok_search_symbol,
    opengrok_search_path,
    opengrok_read_file,
    enter_analyze,
    upsert_artifact,
    exit_analyze,
]

__all__ = [
    "EXT_TOOLS",
    "enter_analyze",
    "upsert_artifact",
    "exit_analyze",
    "jira_search",
    "jira_get",
    "jira_get_transitions",
    "jira_get_projects",
    "jira_get_comments",
    "jira_get_attachments",
    "jira_download_attachment",
    "confluence_search",
    "confluence_get_page",
    "confluence_get_page_by_title",
    "confluence_get_spaces",
    "confluence_get_page_children",
    "confluence_get_attachments",
    "confluence_download_attachment",
    "gerrit_list_changes",
    "gerrit_get_change",
    "gerrit_get_change_detail",
    "gerrit_get_change_diff",
    "gerrit_get_change_messages",
    "gerrit_get_file_content",
    "gerrit_list_projects",
    "gerrit_get_project_branches",
    "opengrok_list_projects",
    "opengrok_search_code",
    "opengrok_search_definition",
    "opengrok_search_symbol",
    "opengrok_search_path",
    "opengrok_read_file",
]
